MD012: false        # Disable multiple consecutive blank lines
MD013: false        # Disable line length rule
MD022: false        # Disable headings should be surrounded by blank lines
MD031: false        # Disable lists should be surrounded by blank lines
MD032: false        # Disable lists should be surrounded by blank lines
MD033: false        # Disable inline HTML rule
MD041: false        # Disable first line heading rule