repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args: [--write]
        additional_dependencies: ['prettier@3.0.0']
        files: \.(js|jsx|json|css|md|mdx|yaml|yml|html)$

  - repo: https://github.com/pre-commit/shellcheck
    rev: v0.9.0
    hooks:
      - id: shellcheck
        files: \.sh$
        