repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ['--ignore-regex="(\b[A-Z]+\b)"', '--ignore-words=.codespell.ignore']
        files: \.mdx?$

  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: npx markdownlint-cli "**/*.md"
        language: system
        files: \.mdx?$